apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pal-tracker
spec:
  rules:
    - host: UNIQUE-DOMAIN-FOR-DEVELOPMENT-ENVIRONMENT
      http:
        paths:
          - path: /
            backend:
              serviceName: pal-tracker
              servicePort: 8080